@startuml
autonumber
actor 图书管理员
图书管理员->图书管理系统:登录
图书管理系统-->图书管理员:登录成功
图书管理系统->图书管理:进入图书管理页面
图书管理->增加或删除图书:进入增加/删除图书页面
loop
图书管理员->增加或删除图书:收到新图书，并在系统内增加图书信息/删除相应图书信息
增加或删除图书-->图书管理员:图书数量增加/减少
end
图书管理员->操作记录:打印操作记录清单
@enduml