@startuml
autonumber
actor 图书管理员
图书管理员->图书管理系统:登录
图书管理系统-->图书管理员:登录成功
图书管理系统->借书页面:进入借书页面
借书页面->用户:输入读者信息
用户-->借书页面:读者信息真实且可借书
loop 至多20次
借书页面->图书:输入书籍信息
图书-->借书页面:该书可借
图书管理员->图书:借出图书，该书数量减一
图书管理员->借书记录:创建借书记录
end
图书管理员->借书记录:打印借书清单
@enduml