@startuml
autonumber
actor 读者
读者->图书管理系统:输入信息
图书管理系统-->读者:登录成功
图书管理系统->预约书籍:进入预约书籍页面
loop 至多20次
预约书籍->图书:输入相关书籍信息
图书-->预约书籍:该书尚有余量可预约
读者->图书:预定该书
图书->读者:成功预定，该书数量减一
图书 -->x 预约书籍:该书已无余量
图书管理系统->预约记录:创建预定记录

end
图书管理系统->预约记录:打印预定清单
@enduml