@startuml
autonumber
actor 图书管理员
图书管理员->图书管理系统:登录
图书管理系统-->图书管理员:登录成功
图书管理系统->还书页面:进入还书页面
还书页面->用户:输入读者信息
用户-->还书页面:读者信息真实且存在未还记录
loop 至多20次
还书页面->图书:录入书籍信息
图书-->还书页面:该书状态为未还且未超期
图书管理员->图书:归还图书，书籍数量加一
图书-->还书页面:借书时间超期
用户->图书管理员:缴纳罚款
图书管理员->缴纳罚款:收取罚款并归入系统账目
缴纳罚款-->图书管理员:系统入账金额
图书管理员->还书记录:创建还书记录
end
图书管理员->还书记录:打印还书清单
@enduml