@startuml
autonumber
actor 图书管理员
图书管理员->图书管理系统:登录
图书管理系统-->图书管理员:登录成功
图书管理系统->读者管理:进入读者管理页面
读者管理->增加或删除或修改读者信息:进入增加/删除/修改读者信息页面
loop
图书管理员->读者:审核读者信息
读者-->图书管理员:读者身份信息正确
图书管理员->增加或删除或修改读者信息:在系统内增加/删除/修改读者信息
增加或删除或修改读者信息->读者:读者数量相应增加或减少或信息修改
增加或删除或修改读者信息-->图书管理员:增加减少修改成功
end
图书管理员->操作记录:打印操作记录清单
@enduml