@startuml

:图书管理员: -up-> (登录)
:图书管理员: -up-> (查阅读者信息)
:图书管理员: -right-> (查询书籍信息)
:图书管理员: -down-> (删除或更新目录)
:图书管理员: -up-> (增加书目)
:图书管理员: -left-> (增加书籍)
:图书管理员: -down-> (删除书籍)
:图书管理员: -down-> (增加读者账户)
:图书管理员: -down-> (删除或更新账户)
(登录) .>(身份验证) : include
@enduml