@startuml

:系统管理员: -up-> (登录系统)
:系统管理员: -up-> (书籍借阅处理)
:系统管理员: -up-> (书籍归还处理)
:系统管理员: -right-> (书籍续借处理)
:系统管理员: -down-> (查询书籍信息)
:系统管理员: -left-> (删除书籍借阅信息)
(登录系统) .>(身份验证) : include
(收取罚金) .>(书籍归还处理) : extends
(查询书籍信息) -left.>(查询是否过期) : include
(查询书籍信息) .>(查询是否可借) : include

@enduml